#
# Copyright (c) 2023 Synapsis.id
#

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - dev
  script:
    - sudo docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
    - sudo bash ./build.sh $CI_COMMIT_BRANCH

deploy-staging:
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  tags:
    - dev
  except:
    - master
  script:
    - sudo bash ./run.sh dev

deploy-prod:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  tags:
    - production
  only:
    - master
  script:
    - sudo bash ./run.sh $CI_COMMIT_BRANCH
  when: manual
