version: '3'
services:
  patronpolitik-fe-dev:
    image: synapsisid/patronpolitik:dev-fe
    container_name: dev_patronpolitik_fe
    restart: always
    ports:
      - 5133:${APP_PORT}
    env_file:
      - .env

networks:
  default:
    external:
      name: gateway_proxymanager
