version: '3'
services:
  patronpolitik-fe:
    image: synapsisid/patronpolitik:${DOCKER_IMG_TAG}
    container_name: patronpolitik_fe
    restart: always
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - traefik_gateway_ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-http.rule=Host(`panel.patronsmonitoring.id`)"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-http.entrypoints=web"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-http.middlewares=redirect-to-https@docker"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-http.service=noop@internal"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-tls.rule=Host(`panel.patronsmonitoring.id`)"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-tls.entrypoints=websecure"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-tls.tls=true"
      - "traefik.http.routers.patronsmonitoring-prod-frontend-tls.service=patronsmonitoring-prod-frontend-svc@docker"
      - "traefik.http.services.patronsmonitoring-prod-frontend-svc.loadbalancer.server.port=3000"

networks:
  traefik_gateway_ingress:
    external: true
