version: '3'
services:
  patronpolitik-fe:
    image: synapsisid/patronpolitik:${DOCKER_IMG_TAG}
    container_name: patronpolitik_fe
    restart: always
    ports:
      - 127.0.0.1:${APP_PORT}:${APP_PORT}
    env_file:
      - .env

networks:
  default:
    external:
      name: gateway_proxymanager
