export const dummyTable = {
  data: [
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
    {
      name: "Kecelakaan Mobil",
      category_name: "Kejahatan ",
      sub_category: "Pencurian",
      type: "Tematik",
      month: "Juni",
      year: "2022",
      upload_date: "24 Mei 2023, 23:29:02",
    },
  ],
};
